version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '33061:3306'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./mysql_conf:/etc/mysql/conf.d
      - mysql80-data-development:/var/lib/mysql
volumes:
  mysql80-data-development:
    driver: local
